apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: kuldeeps-cicd-pipeline
  workspaces:
    - name: kuldeeps-workspace
      #persistentVolumeClaim:
       # claimName: kuldeep-singh-live-pvc
      volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi