apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: squad2-evnt-lstnr
spec:
  serviceAccountName: triggers-sa
  triggers:
    - bindings:
        - ref: squad2-triggerbinding
      template:
        name: squad2-triggertemplate