apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: squad2-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: squad2-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: squad2-project-pipeline
        workspaces:
          - name: squad2-workspace
            #persistentVolumeClaim:
            # claimName: kuldeep-singh-live-pvc
            volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi