apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuldeep-singh-pipeline-from-scratch
commonAnnotations:
  enzo: "true"
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml